#!/usr/bin/env bash

# Start docker-gen
docker-gen -config /runtime/docker-gen.conf &
DOCKER_GEN_PID=$!

# Start caddy
caddy run --adapter caddyfile --config /etc/caddy/Caddyfile &
CADDY_PID=$!

# Stop services
trap 'echo SIGINT; kill -s SIGINT $DOCKER_GEN_PID $CADDY_PID' SIGINT
trap 'echo SIGTERM; kill -s SIGTERM $DOCKER_GEN_PID $CADDY_PID' SIGTERM

# Wait for any process to exit
wait -n

# Exit with status of process that exited first
exit $?
