services:
  proxy:
    build:
      context: ./src
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:rw
    environment:
      PROXY_HTTP_PORT: 9080
      PROXY_HTTPS_PORT: 9443
    network_mode: "host"

  web:
    image: jwilder/whoami
    environment:
      SP_PROXY_HOST: whoami.d1x.sitepilot.io

  web2:
    image: nginx
    environment:
      SP_PROXY_HOST: whoami.d1x.sitepilot.io

  web3:
    image: jwilder/whoami
    environment:
      SP_PROXY_HOST: whoami.d1x.sitepilot.io

  stream1:
    image: jwilder/whoami
    environment:
      SP_PROXY_PORT: 9081

  stream2:
    image: jwilder/whoami
    environment:
      SP_PROXY_PORT: 9081

  stream3:
    image: jwilder/whoami
    environment:
      SP_PROXY_PORT: 9081
