services:
  proxy:
    build:
      context: ./src
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:rw
    ports:
      - 9080:80
      - 9443:443

  web:
    image: jwilder/whoami
    environment:
      PROXY_HTTP_HOST: whoami.d1x.sitepilot.io
      PROXY_HTTP_UPSTREAMS: 1.2.3.4:80,1.2.3.5:80

  web2:
    image: jwilder/whoami
    environment:
      PROXY_HTTP_HOST: whoami.d1x.sitepilot.io

  web3:
    image: jwilder/whoami
    environment:
      PROXY_HTTP_HOST: whoami.d1x.sitepilot.io
